// SPDX-License-Identifier: MIT
pragma solidity ^0.8.7;
pragma abicoder v2;

/*
Functions here are stubs for the solidity compiler to generate the right interface.
The deployed library is generated bytecode from the circomlib toolchain
*/

library PoseidonT6 {
    // solhint-disable-next-line no-empty-blocks
    function poseidon(bytes32[5] memory input) internal pure returns (bytes32) {}
}
